Data Types & Attributes

In [1]:
# 1. Create a NumPy array arr of integers from 0 to 5 and print its data type.

In [1]:
import numpy as np

arr = np.arange(6)
print(arr, arr.dtype)

[0 1 2 3 4 5] int32


In [2]:
# 2. Given a NumPy array arr, check if its data type is float64.

In [3]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
arr2 = np.array([1.0, 2.1, 3.2, 4.3, 5.4])
print("data type is float" if arr.dtype == np.float64 else "data type is not float")
print("data type is float" if arr2.dtype == np.float64 else "data type is not float")

data type is not float
data type is float


In [3]:
# 3. Create a NumPy array arr with a data type of complex128 containing three complex numbers.

In [5]:
import numpy as np

arr = np.array([1j, 2+3j, (4j)*(5+6j)], dtype=np.complex128)
print(arr)

[  0. +1.j   2. +3.j -24.+20.j]


In [4]:
# 4. Convert an existing NumPy array arr of integers to float32 data type.

In [6]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
float_arr = arr.astype(np.float32)
print(float_arr)

[1. 2. 3. 4. 5.]


In [5]:
# 5. Given a NumPy array arr with float64 data type, convert it to float32 to reduce decimal precision.

In [9]:
import numpy as np

float64_arr = np.array([1.23456789, 2.34567891011, 3.456789101112], dtype=np.float64)
float32_arr = float64_arr.astype(np.float32)
print(float32_arr)

[1.2345679 2.3456788 3.456789 ]


In [6]:
# 6. Write a function array_attributes that takes a NumPy array as input and returns its shape, size, and data type.

In [10]:
import numpy as np

def array_attributes(arr):
    return arr.shape, arr.size, arr.dtype

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
result = array_attributes(arr)
print(result)

((3, 3), 9, dtype('int32'))


In [7]:
# 7. Create a function array_dimension that returns the dimensionality of a NumPy array.

In [12]:
import numpy as np

def array_dimension(arr):
    return arr.ndim

arr = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]]])
result = array_dimension(arr)
print(result)

3


In [8]:
# 8. Design a function item_size_info that returns the item size and total size in bytes of a NumPy array.

In [13]:
import numpy as np

def item_size_info(arr):
    return arr.itemsize, arr.nbytes

arr = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]]])
item_size, total_size = item_size_info(arr)
print(item_size, total_size)

4 36


In [9]:
# 9. Create a function array_strides that returns the strides of the given NumPy array.

In [14]:
import numpy as np

def array_strides(arr):
    return arr.strides

arr = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]]])
result = array_strides(arr)
print(result)

(36, 12, 4)


In [10]:
# 10. Design a function shape_stride_relationship that returns the shape and strides of the given array.

In [15]:
import numpy as np

def shape_stride_relationship(arr):
    return arr.shape, arr.strides

arr = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]]])
shape, strides = shape_stride_relationship(arr)
print(shape, strides)

(1, 3, 3) (36, 12, 4)


Array Creation

In [11]:
# 11. Create a function create_zeros_array(n) to return a NumPy array of zeros with n elements.

In [16]:
import numpy as np

def create_zeros_array(n):
    return np.zeros(n)

arr = create_zeros_array(9)
print(arr)

[0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [12]:
# 12. Write a function create_ones_matrix(rows, cols) to create a 2D array filled with ones.

In [17]:
import numpy as np

def create_ones_matrix(rows, cols):
    return np.ones((rows, cols))

matrix = create_ones_matrix(2, 2)
print(matrix)

[[1. 1.]
 [1. 1.]]


In [13]:
# 13. Write a function generate_range_array(start, stop, step) to create a ranged NumPy array.

In [18]:
import numpy as np

def generate_range_array(start, stop, step):
    return np.arange(start, stop, step)

arr = generate_range_array(1, 21, 3)
print(arr)

[ 1  4  7 10 13 16 19]


In [14]:
# 14. Design a function generate_linear_space(start, stop, num) for equally spaced values.

In [21]:
import numpy as np

def generate_linear_space(start, stop, num):
    return np.linspace(start, stop, num)

arr = generate_linear_space(0, 10, 20)
print(arr)

[ 0.          0.52631579  1.05263158  1.57894737  2.10526316  2.63157895
  3.15789474  3.68421053  4.21052632  4.73684211  5.26315789  5.78947368
  6.31578947  6.84210526  7.36842105  7.89473684  8.42105263  8.94736842
  9.47368421 10.        ]


In [15]:
# 15. Create a function create_identity_matrix(n) using numpy.eye.

In [22]:
import numpy as np

def create_identity_matrix(n):
    return np.eye(n)

matrix = create_identity_matrix(3)
print(matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [16]:
# 16. Write a function that converts a Python list into a NumPy array.

In [26]:
import numpy as np

def convert_list_into_a_numpy_array(lst):
    return np.array(lst)

lst = [1, 2, 3, 4, 5]
arr = convert_list_into_a_numpy_array(lst)
print(arr, type(arr))

[1 2 3 4 5] <class 'numpy.ndarray'>


In [17]:
# 17. Create a NumPy array and use numpy.view() to create a new view with the same data.

In [27]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
arr_view = arr.view()
print(arr_view)

[1 2 3 4 5]


Concatenation and Stacking

In [18]:
# 18. Write a function to concatenate two NumPy arrays along a specified axis.

In [34]:
import numpy as np

def concatenate_two_numpy_arrays(arr, arr2, axis_value):
    return np.concatenate((arr, arr2), axis=axis_value)

arr = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
result_axis_0 = concatenate_two_numpy_arrays(arr, arr2, 0)
result_axis_1 = concatenate_two_numpy_arrays(arr, arr2, 1)
print(result_axis_0, '\n\n', result_axis_1)

[[1 2]
 [3 4]
 [5 6]
 [7 8]] 

 [[1 2 5 6]
 [3 4 7 8]]


In [19]:
# 19. Concatenate two arrays with different shapes horizontally using numpy.concatenate.

In [37]:
import numpy as np

arr = np.array([[1, 3], [5, 7]])
arr2 = np.array([[2, 4], [6, 8]])
result = np.concatenate((arr, arr2), axis=1)
print(result)

[[1 3 2 4]
 [5 7 6 8]]


In [20]:
# 20. Vertically stack multiple arrays from a list using numpy.vstack.

In [39]:
import numpy as np

arrs = [np.array([1, 2]), np.array([3, 4]), np.array([5, 6]), np.array([7, 8]), np.array([9, 0])]
result = np.vstack(arrs)
print(result)

[[1 2]
 [3 4]
 [5 6]
 [7 8]
 [9 0]]


Array Generation

In [21]:
# 21. Write a function to generate an array of integers within a specified range (inclusive) with a step.

In [40]:
import numpy as np

def generate_an_array_of_integers_within_a_range(start, stop, step=1):
    return np.arange(start, stop + (1 if step > 0 else -1), step)

arr = generate_integer_range(1, 10, 20)
print(arr)

[1]


In [22]:
# 22. Generate 10 equally spaced values between 0 and 1 using NumPy.

In [42]:
import numpy as np

arr = np.linspace(0, 1, 10)
print(arr)

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


In [23]:
# 23. Create 5 logarithmically spaced values between 1 and 1000.

In [3]:
import numpy as np

arr = np.logspace(0, 3, 5)
print(arr)

[   1.            5.62341325   31.6227766   177.827941   1000.        ]


Pandas + NumPy

In [24]:
# 24. Create a Pandas DataFrame from a NumPy array with 5 rows and 3 columns of random integers (1-100).

In [5]:
import numpy as np
import pandas as pd

arr = np.random.randint(1, 101, size=(5, 3))
df = pd.DataFrame(arr, columns=[1, 2, 3])
print(df)

    1   2   3
0  60  95  30
1  16  89  78
2  77  81  85
3  13  59  37
4  64  27  51


In [25]:
# 25. Write a function to replace all negative values in a specific column with zeros using NumPy.

In [8]:
import numpy as np

def replace__all_negative_values_with_zeros(arr, indx):
    arr[:, indx] = np.where(arr[:, indx] < 0, 0, arr[:, indx])
    return arr

arr = np.array([[-1, 2, -3],[4, -5, 6],[-7, -8, 9]])
result = replace__all_negative_values_with_zeros(arr, 1)
print(result)

[[-1  2 -3]
 [ 4  0  6]
 [-7  0  9]]


Indexing and Slicing

In [26]:
# 26. Access the 3rd element from the given NumPy array.

In [9]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
print(arr[2])

3


In [27]:
# 27. Retrieve the element at index (1, 2) from a 2D array.

In [10]:
import numpy as np

arr = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
print(arr[1, 2])

60


In [28]:
# 28. Extract elements greater than 5 using boolean indexing.

In [11]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 0])
print(arr[arr > 5])

[6 7 8 9]


In [31]:
# 29. Slice elements from index 2 to 5 (inclusive) from a NumPy array.

In [12]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 0])
print(arr[2:6])

[3 4 5 6]


In [32]:
# 30. Slice the sub-array [[2, 3], [5, 6]] from a 2D array.

In [14]:
import numpy as np

arr = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9,]])
print(arr[0:2, 1:3])

[[2 3]
 [5 6]]


Advanced Indexing


In [33]:
# 31. Extract elements based on indices from a 2D array.

In [18]:
import numpy as np

arr = np.array([[1, 2, 3, 0], [4, 5, 6, 0], [7, 8, 9, 0], [10, 11, 12, 0]])
print(arr[np.array([0, 1, 3]), np.array([0, 2, 3])])

[1 6 0]


In [34]:
# 32. Filter elements greater than a threshold using boolean indexing.

In [19]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 0])
print(arr[arr > 5])

[6 7 8 9]


In [35]:
# 33. Extract specific elements from a 3D array using separate index arrays.

In [25]:
import numpy as np

arr = np.array([[[1, 2, 3, 0], [4, 5, 6, 0], [7, 8, 9, 0]], [[11, 12, 13, 10], [14, 15, 16, 10], [17, 18, 19, 10]]])
print(arr[np.array([0, 1]), np.array([0, 2]), np.array([0, 2])])

[ 1 19]


In [36]:
# 34. Return elements satisfying two boolean conditions.

In [26]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 0])
print(arr[(arr > 1) & (arr < 7)])

[2 3 4 5 6]


In [37]:
# 35. Extract elements from a 2D array using separate row and column index arrays.

In [27]:
import numpy as np

arr = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
print(arr[np.array([0, 1, 2]), np.array([2, 1, 0])])

[3 5 7]


Broadcasting

In [38]:
# 36. Add scalar 5 to every element of an array using broadcasting.

In [28]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8,  9]])
print(5 + arr)

[[ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


In [39]:
# 37. Multiply each row of a (3, 4) array by corresponding elements of a (1, 3) array.

In [39]:
import numpy as np

arr = np.array([[1, 2, 3, 0], [4, 5, 6, 0], [7, 8, 9, 0]])
print(np.array([[1], [2], [3]]) * arr)

[[ 1  2  3  0]
 [ 8 10 12  0]
 [21 24 27  0]]


In [40]:
# 38. Add a (1, 4) array to every row of a (4, 3) array using broadcasting.

In [40]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
print(np.array([[1, 2, 3, 4]]).transpose() + arr)

[[ 2  3  4]
 [ 6  7  8]
 [10 11 12]
 [14 15 16]]


In [41]:
# 39. Add two arrays of shapes (3, 1) and (1, 3) using broadcasting.

In [41]:
import numpy as np

arr = np.array([[1], [2], [3]])
arr2 = np.array([[7, 8, 9]])
print(arr + arr2)

[[ 8  9 10]
 [ 9 10 11]
 [10 11 12]]


In [42]:
# 40. Handle shape incompatibility during multiplication between (2, 3) and (2, 2) arrays.

In [47]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[7, 8], [9, 0]])
print(np.dot(arr2, arr))

[[39 54 69]
 [ 9 18 27]]


Aggregations and Statistics

In [43]:
# 41. Calculate column-wise mean of a 2D array.

In [48]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(np.mean(arr, axis=0))

[4. 5. 6.]


In [44]:
# 42. Find maximum value in each row.

In [49]:
import numpy as np

arr = np.array([[1, 5, 2], [9, 3, 6], [7, 4, 8]])
print(np.max(arr, axis=1))

[5 9 8]


In [45]:
# 43. Find indices of maximum values in each column.

In [52]:
import numpy as np

arr = np.array([[1, 5, 2], [9, 3, 6], [7, 4, 8]])
print(np.argmax(arr, axis=0))

[1 0 2]


In [60]:
# 44. Apply a custom function to compute moving sum along rows.

In [66]:
import numpy as np

def moving_sum_along_rows(x, window=3):
    return np.convolve(x, np.ones(window, dtype=int), 'valid')
    
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
result = np.apply_along_axis(moving_sum_along_rows, axis=1, arr=arr)
print(result)

[[ 6]
 [15]
 [24]]


In [61]:
# 45. Check if all elements in each column are even.

In [3]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 6, 8], [9, 12, 15]])
result = np.all(arr % 2 == 0, axis=0)
print(result)

[False  True False]


Reshaping and Flattening

In [62]:
# 46. Reshape a given array into dimensions m x n.

In [5]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 0])
print(arr.reshape(2, 5))

[[1 2 3 4 5]
 [6 7 8 9 0]]


In [63]:
# 47. Return a flattened version of a given matrix.

In [8]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr.reshape(-1))

[1 2 3 4 5 6 7 8 9]


In [50]:
# 48. Concatenate two arrays along a specified axis.

In [11]:
import numpy as np

arr = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
print(np.concatenate((arr, arr2), axis=0), '\n\n', np.concatenate((arr, arr2), axis=1))

[[1 2]
 [3 4]
 [5 6]
 [7 8]] 

 [[1 2 5 6]
 [3 4 7 8]]


In [51]:
# 49. Split an array into sub-arrays along a specified axis.

In [14]:
import numpy as np
arr = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
result_along_rows = np.split(arr, 3, axis=0)
result_along_columns = np.split(arr, 3, axis=1)
print(result_along_rows, '\n\n', result_along_columns)

[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])] 

 [array([[1],
       [4],
       [7]]), array([[2],
       [5],
       [8]]), array([[3],
       [6],
       [9]])]


In [52]:
# 50. Insert and delete elements at specified indices from an array.

In [16]:
import numpy as np

arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
print(np.insert(arr, 10, 10), '\n\n', np.delete(arr, 0))

[ 0  1  2  3  4  5  6  7  8  9 10] 

 [1 2 3 4 5 6 7 8 9]


Element-wise Operations

In [53]:
# 51. Perform element-wise addition between two arrays.

In [17]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
arr2 = np.array([6, 7, 8, 9, 0])
print(arr + arr2)

[ 7  9 11 13  5]


In [54]:
# 52. Perform element-wise subtraction: subtract arr2 from arr1.

In [18]:
import numpy as np

arr1 = np.array([6, 7, 8, 9, 0])
arr2 = np.array([1, 2, 3, 4, 5])
print(arr1 - arr2)

[ 5  5  5  5 -5]


In [55]:
# 53. Perform element-wise multiplication.

In [19]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
arr2 = np.array([6, 7, 8, 9, 0])
print(arr * arr2)

[ 6 14 24 36  0]


In [56]:
# 54. Divide elements of arr1 by arr2 element-wise.

In [20]:
import numpy as np

arr1 = np.array([6, 7, 8, 9, 0])
arr2 = np.array([1, 2, 3, 4, 5])
print(arr1 / arr2)

[6.         3.5        2.66666667 2.25       0.        ]


In [57]:
# 55. Perform element-wise exponentiation: arr1 ** arr2.

In [21]:
import numpy as np

arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([6, 7, 8, 9, 0])
print(arr1 ** arr2)

[     1    128   6561 262144      1]


String Operations

In [58]:
# 56. Count occurrences of a substring in a string array.

In [24]:
import numpy as np

arr = np.array(['apple', 'rubber', 'hyper', 'blackberry', 'cyber fiber'])
substring_value = 'ber'
print(np.char.count(arr, substring_value))

[0 1 0 1 2]


In [59]:
# 57. Extract uppercase characters from a string array.

In [26]:
import numpy as np

words = np.array(['Hello', 'How Are You?', 'I AM FINE', 'BYE'])
result = [''.join([char for char in word if char.isupper()]) for word in words]
print(result)

['H', 'HAY', 'IAMFINE', 'BYE']


In [60]:
# 58. Replace substring occurrences with another string in a string array.

In [27]:
import numpy as np

arr = np.array(['apple', 'rubber', 'hyper', 'blackberry', 'cyber fiber'])
substring_value = 'ber'
new_substring_value = 'na'
print(np.char.replace(arr, substring_value, new_substring_value))

['apple' 'rubna' 'hyper' 'blacknary' 'cyna fina']


In [61]:
# 59. Concatenate strings in a NumPy array element-wise.

In [31]:
import numpy as np

arr = np.array(['Hello', 'WelcomeTo', 'Learn'])
arr2 = np.array(['World!', 'Python', 'AI'])
print(np.char.add(arr, arr2))

['HelloWorld!' 'WelcomeToPython' 'LearnAI']


In [62]:
# 60. Find the length of the longest string in a string array.

In [32]:
import numpy as np

arr = np.array(['Hello', 'World!', 'WelcomeTo', 'Python', 'Learn', 'AI'])
print(np.max(np.char.str_len(arr)))

9


Descriptive Statistics

In [63]:
# 61. Generate 100 random integers (1–1000) and compute mean, median, variance, and std deviation.

In [46]:
import numpy as np

data = np.random.randint(1, 1001, size=100)
print(data, '\n')
print(np.mean(data), '\n')
print(np.median(data), '\n')
print(np.var(data), '\n')
print(np.std(data))

[794 116 787 118 565  83 398 251 848 257 104 726 751  24 792 493 947 428
 827 106 688 371 655 375 920 691 595  74  13 233 343 789  67 489 563 679
 208 369 523 875 993 411 875 353 544 837 378 114 363 335 915 322   9 499
 149 968 908 331 458 472 312 919 990  12  22  84 175 694 926 518 516 316
 816 168 353 748 146 539 504 328 531 694  84 275  32 534 625 204 772 615
 900 112 844 243 790 964  73 785 817 884] 

490.33 

496.0 

89138.8611 

298.56131882747303


In [64]:
# 62. Generate 50 random numbers (1–100) and compute the 25th and 75th percentiles.

In [45]:
import numpy as np

data = np.random.randint(1, 101, size=50)
print(data, '\n')
print(np.percentile(data, 25), '\n')
print(np.percentile(data, 75))

[72 54 41 85 59 76 38  8 32 69 43 88 22 89  7 83 51 26 41 70 83 25 82 77
 65 58 20 19 25 46 96 52 27 46 36 95 41 21 86 28 11 82 17 12 51 70 64  8
 72 95] 

26.25 

75.0


In [65]:
# 63. Compute correlation coefficient between two arrays using np.corrcoef.

In [44]:
import numpy as np

arr = np.array([1, 2, 3])
arr2 = np.array([4, 6, 8])
print(np.corrcoef(arr, arr2), '\n')
print(np.corrcoef(arr, arr2)[0, 1])

[[1. 1.]
 [1. 1.]] 

1.0


In [66]:
# 64. Perform matrix multiplication using np.dot.

In [47]:
import numpy as np

arr = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
print(np.dot(arr, arr2))

[[19 22]
 [43 50]]


In [67]:
# 65. Compute the 10th, 50th, and 90th percentiles and quartiles for an array of 50 integers.

In [48]:
import numpy as np

data = np.random.randint(1, 101, size=50)

p10 = np.percentile(data, 10)
p50 = np.percentile(data, 50)
p90 = np.percentile(data, 90)

q1 = np.percentile(data, 25)
q3 = np.percentile(data, 75)

print(data, '\n')
print(np.percentile(data, 10), '\n')
print(np.percentile(data, 50), '\n')
print(np.percentile(data, 90), '\n')
print(np.percentile(data, 25), '\n')
print(np.percentile(data, 75))

[92 48 35 32 50 42 16 96 31 30 18 72 82  6 17 26 91 95 21 55 18 76 81 69
 81 63 38 69  9 36 64 53 89 31 13 77 78 63 27 50 28 50 35  6 49 52 38 86
 93  9] 

15.700000000000001 

49.5 

89.2 

28.5 

75.0


Search and Sort

In [68]:
# 66. Find index of a specific element in an array.

In [51]:
import numpy as np

arr = np.array([0, 1, 1, 2, 3, 5, 8])
print(np.where(arr == 1)[0][0])

1


In [69]:
# 67. Sort a random array in ascending order.

In [53]:
import numpy as np

arr = np.random.randint(1, 21, size=20)
print(arr, '\n')
print(np.sort(arr))

[ 8 12  5 14  7  8  7  4  2  4  1 17 18  9  7 18  3 15  6 20] 

[ 1  2  3  4  4  5  6  7  7  7  8  8  9 12 14 15 17 18 18 20]


In [70]:
# 68. Filter elements greater than 20.

In [55]:
import numpy as np

arr = np.random.randint(1, 51, size=20)
print(arr, '\n')
print(arr[arr > 20])

[30 17 36  6 28 31  1  1 48 43 44 36 21 48 12 37 11 27 25 14] 

[30 36 28 31 48 43 44 36 21 48 37 27 25]


In [71]:
# 69. Filter elements divisible by 3.

In [56]:
import numpy as np

arr = np.random.randint(1, 51, size=20)
print(arr, '\n')
print(arr[arr % 3 == 0])

[12 23 30 26 13 31 12 20 42 43 22 12 47  4 40 17 33 41 34  7] 

[12 30 12 42 12 33]


In [72]:
# 70. Filter elements between 20 and 40 (inclusive).

In [57]:
import numpy as np

arr = np.random.randint(1, 51, size=20)
print(arr, '\n')
print(arr[(arr >= 20) & (arr <= 40)])

[31 15 10 26 31 36 18  6 46  6 36 25  9 50 36  5 47 39  6 44] 

[31 26 31 36 36 25 36 39]


Byte Order & Swapping

In [58]:
# 71. Check byte order of a NumPy array using dtype.byteorder.

In [35]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
print(arr.dtype.byteorder)

=


In [59]:
# 72. Perform in-place byte swapping using byteswap().

In [39]:
import numpy as np

arr = np.array([4, 64, 2, 8, 256])
arr.byteswap(inplace=True)
print(arr)

[  67108864 1073741824   33554432  134217728      65536]
